services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.time_provider:
      class: DateTimeImmutable

  app.services.payments:
      class: SupportService\Service\PaymentsService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.time_provider"
          - "@logger"
