services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.time_provider:
      class: DateTimeImmutable
